import React,{useEffect,useRef,useState} from 'react';
import {Plus,Download,Upload,Search,ScanBarcode,Package,PenLine,Trash2,ArrowDown,ArrowUp,ChevronsUpDown,RotateCcw,AlertTriangle} from 'lucide-react';
import {useApp,useData,api,Money,Button,Modal,ErrorBox} from '../main.jsx';
import {Barcode} from '../pages.jsx';
import {catalogText} from '../catalog-i18n.js';
import {stockStatus,unitText} from '../../shared/catalog.js';
import ProductForm from './ProductForm.jsx';
import ImportProducts from './ImportProducts.jsx';
import Scanner from './Scanner.jsx';
import StockEditor from './StockEditor.jsx';

export default function Products(){
  const {lang,toast}=useApp(),t=(s,v)=>catalogText(s,lang,v);
  const [categories,loadCategories]=useData('/categories'),[brands,loadBrands]=useData('/brands'),[suppliers,loadSuppliers]=useData('/suppliers');
  const [query,setQuery]=useState(''),[search,setSearch]=useState(''),[category,setCategory]=useState(''),[stock,setStock]=useState('all'),[sort,setSort]=useState('name'),[direction,setDirection]=useState('asc'),[page,setPage]=useState(1),[size,setSize]=useState(20),[revision,setRevision]=useState(0);
  const [result,setResult]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[edit,setEdit]=useState(null),[label,setLabel]=useState(null),[remove,setRemove]=useState(null),[deleting,setDeleting]=useState(false),[deleteError,setDeleteError]=useState(''),[importOpen,setImportOpen]=useState(false),[scan,setScan]=useState(false);
  const [stockEdit,setStockEdit]=useState(null);
  const searchInput=useRef();
  useEffect(()=>{const refresh=()=>{if(!document.hidden)setRevision(r=>r+1);};const timer=setInterval(refresh,15000);window.addEventListener('focus',refresh);window.addEventListener('retail-data-changed',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('retail-data-changed',refresh);};},[]);
  const [exactBarcode,setExactBarcode]=useState('');
  useEffect(()=>{const timer=setTimeout(()=>{setSearch(query);setPage(1);},250);return()=>clearTimeout(timer);},[query]);
  useEffect(()=>{
    const controller=new AbortController();if(!result)setLoading(true);setError('');
    const parameters=new URLSearchParams({q:search,...(exactBarcode?{barcode:exactBarcode}:{}),stock,sort,direction,page:String(page),size:String(size),...(category?{category}:{})});
    fetch('/api/catalog?'+parameters,{signal:controller.signal}).then(async r=>{const data=await r.json();if(!r.ok)throw new Error(data.error);return data;}).then(data=>{setResult(data);setLoading(false);}).catch(e=>{if(e.name!=='AbortError'){setError(e.message);setLoading(false);}});
    return()=>controller.abort();
  },[search,exactBarcode,stock,category,sort,direction,page,size,revision]);
  const reload=()=>{setRevision(r=>r+1);loadCategories();loadBrands();loadSuppliers();};
  const reset=()=>{setExactBarcode('');setQuery('');setSearch('');setCategory('');setStock('all');setPage(1);};
  const sortBy=column=>{setDirection(sort===column&&direction==='asc'?'desc':'asc');setSort(column);setPage(1);};
  const filters=!!query||!!category||stock!=='all';
  const summary=result?.summary;
  const badge=p=>{const status=stockStatus(p);return <div className="stock-cell"><span className={'stock-badge '+status}>{t(status==='out'?'Out of stock':status==='low'?'Low stock':'In stock')}</span><span>{unitText(p.quantity,p.unit,lang)}</span><small>{t('Minimum: {count}',{count:p.min_stock})}</small><button className="text-btn" type="button" aria-label={t('Update stock')+': '+p.name} onClick={()=>setStockEdit(p)}>{t('Update stock')}</button></div>;};
  const actions=p=><div className="catalog-row-actions" aria-label={t('Product actions')}>
    {[[PenLine,'Edit product',()=>setEdit(p)],[ScanBarcode,'Barcode labels',()=>setLabel(p)],[Trash2,'Delete product',()=>{setDeleteError('');setRemove(p);}]].map(([Icon,text,action])=><button key={text} type="button" className={'icon-btn '+(text==='Delete product'?'danger':'')} aria-label={`${t(text)}: ${p.name}`} title={t(text)} onClick={action}><Icon size={18}/>{text==='Delete product'&&<span>{t('Delete')}</span>}<span className="action-tooltip" role="tooltip">{t(text)}</span></button>)}
  </div>;
  const headers=[['name','Product'],['category','Category'],['purchase_price','Cost'],['selling_price','Price'],['quantity','Stock']];
  return <div className="catalog-page">
    <header className="catalog-heading"><div><h1>{t('Products')}</h1><p>{t('Your catalog, ready for the next sale.')}</p></div><div className="catalog-heading-actions"><div className="excel-actions" role="group" aria-label={t('Excel actions')}><Button variant="secondary" icon={Upload} onClick={()=>setImportOpen(true)}>{t('Import Excel')}</Button><a className="btn secondary" href="/api/products/export.xlsx"><Download size={17}/>{t('Export Excel')}</a></div><Button icon={Plus} onClick={()=>setEdit({})}>{t('Add product')}</Button></div></header>
    <div className="catalog-summary" aria-live="polite">{[['Total products','total',Package,'all'],['Low stock','low',AlertTriangle,'low'],['Out of stock','out',Package,'out']].map(([name,key,Icon,filter])=><button key={key} className={stock===filter?'selected':''} aria-pressed={stock===filter} onClick={()=>{setStock(filter);setPage(1);}}><span className={'summary-icon '+key}><Icon size={20}/></span><span>{t(name)}<strong>{summary?summary[key].toLocaleString():'—'}</strong></span></button>)}</div>
    <section className="panel catalog-panel" aria-label={t('Products')}>
      <div className="catalog-filters"><form className="catalog-search" onSubmit={e=>{e.preventDefault();setExactBarcode('');setSearch(query.trim());setPage(1);}}><Search size={20}/><input ref={searchInput} aria-label={t('Search name, SKU or barcode')} placeholder={t('Search name, SKU or barcode')} value={query} maxLength={200} onChange={e=>{setExactBarcode('');setQuery(e.target.value);}}/>{query&&<button type="button" aria-label={t('Reset search')} title={t('Reset search')} onClick={()=>{setExactBarcode('');setQuery('');setSearch('');setPage(1);searchInput.current.focus();}}>×</button>}</form><Button variant="secondary" icon={ScanBarcode} onClick={()=>setScan(true)}>{t('Scan barcode')}</Button>
        <label><span>{t('Category')}</span><select value={category} onChange={e=>{setCategory(e.target.value);setPage(1);}}><option value="">{t('All categories')}</option>{categories?.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label>
        <label><span>{t('Stock status')}</span><select value={stock} onChange={e=>{setStock(e.target.value);setPage(1);}}>{[['all','All stock'],['in','In stock'],['low','Low stock'],['out','Out of stock']].map(([value,text])=><option value={value} key={value}>{t(text)}</option>)}</select></label>
        <Button variant="secondary" icon={RotateCcw} disabled={!filters} onClick={reset}>{t('Reset filters')}</Button>
      </div>
      <div className="mobile-sort"><label>{t('Sort by {column}',{column:''})}<select value={sort} onChange={e=>sortBy(e.target.value)}>{headers.map(([key,name])=><option key={key} value={key}>{t(name)}</option>)}</select></label><Button variant="secondary" aria-label={t(direction==='asc'?'Ascending':'Descending')} onClick={()=>setDirection(d=>d==='asc'?'desc':'asc')}>{direction==='asc'?<ArrowUp size={18}/>:<ArrowDown size={18}/>}</Button></div>
      {error?<div className="catalog-state"><ErrorBox error={t('Could not load the catalog.')+' '+t(error)}/><Button variant="secondary" onClick={()=>setRevision(r=>r+1)}>{t('Try again')}</Button></div>:loading?<div className="catalog-skeleton" role="status" aria-label={t('Loading products…')}><p>{t('Loading products…')}</p>{Array.from({length:6},(_,i)=><div key={i}/>)}</div>:!result?.items.length?<div className="catalog-state"><Package size={36}/><h2>{t(result?.summary.total?'No matching products':'No products yet')}</h2><p>{t(result?.summary.total?'Try another search or reset your filters.':'Add your first product to start building your catalog.')}</p><Button onClick={result?.summary.total?reset:()=>setEdit({})}>{t(result?.summary.total?'Reset filters':'Add product')}</Button></div>:<>
        <div className="catalog-table-scroll desktop-catalog" tabIndex={0} aria-label={t('Products')}><table className="catalog-table"><thead><tr>{headers.map(([key,name])=><th scope="col" key={key} aria-sort={sort===key?(direction==='asc'?'ascending':'descending'):'none'} className={key.includes('price')?'numeric':''}><button onClick={()=>sortBy(key)} title={t('Sort by {column}',{column:t(name)})}>{t(name)}{sort===key?(direction==='asc'?<ArrowUp size={14}/>:<ArrowDown size={14}/>):<ChevronsUpDown size={14}/>}</button></th>)}<th scope="col">{t('Actions')}</th></tr></thead><tbody>{result.items.map(p=><tr key={p.id}><td><div className="product-cell"><span className="mini-product">{p.image?<img src={p.image} alt="" loading="lazy"/>:<Package size={22}/>}</span><div><strong>{p.name}</strong><small>{t('SKU')}: {p.code}</small><small>{t('Barcode')}: {p.barcode}</small></div></div></td><td>{p.category||t('No category')}</td><td className="numeric"><Money value={p.purchase_price}/></td><td className="numeric selling-price"><Money value={p.selling_price}/></td><td>{badge(p)}</td><td>{actions(p)}</td></tr>)}</tbody></table></div>
        <div className="mobile-product-list">{result.items.map(p=><article key={p.id}><div className="mobile-product-heading"><div><h2>{p.name}</h2><p>{t('SKU')}: {p.code}</p><p>{p.category||t('No category')}</p></div><strong><Money value={p.selling_price}/></strong></div><div className="mobile-product-bottom">{badge(p)}{actions(p)}</div><details><summary>{t('Product details')}</summary><dl><dt>{t('Barcode')}</dt><dd>{p.barcode}</dd><dt>{t('Cost')}</dt><dd><Money value={p.purchase_price}/></dd></dl></details></article>)}</div>
      </>}
      {result&&!error&&<div className="catalog-pagination" aria-label={t('Pagination')}><span aria-live="polite">{t('Showing {from}–{to} of {total}',{from:result.total?(result.page-1)*result.size+1:0,to:Math.min(result.page*result.size,result.total),total:result.total})}</span><label>{t('Rows per page')}<select value={size} onChange={e=>{setSize(Number(e.target.value));setPage(1);}}>{[20,50,100].map(n=><option key={n}>{n}</option>)}</select></label><div className="pagination-buttons"><Button variant="secondary" disabled={loading||result.page<=1} onClick={()=>setPage(result.page-1)}>{t('Previous')}</Button><span>{t('Page {page} of {pages}',{page:result.page,pages:result.pages})}</span><Button variant="secondary" disabled={loading||result.page>=result.pages} onClick={()=>setPage(result.page+1)}>{t('Next')}</Button></div></div>}
    </section>
    {stockEdit&&<StockEditor product={stockEdit} onClose={()=>setStockEdit(null)} onSaved={()=>{reload();toast(t('Stock updated.'));}}/>}
    {edit&&<ProductForm product={edit} categories={categories||[]} brands={brands||[]} suppliers={suppliers||[]} onClose={()=>setEdit(null)} onSaved={()=>{reload();toast(t('Product saved.'));}}/>}
    {importOpen&&<ImportProducts categories={categories||[]} brands={brands||[]} suppliers={suppliers||[]} onClose={()=>setImportOpen(false)} onSaved={count=>{reload();toast(t('Imported {count} products.',{count}));}}/>}
    {label&&<Barcode product={label} onClose={()=>setLabel(null)}/>}
    {scan&&<Scanner onClose={()=>setScan(false)} onScan={code=>{setExactBarcode(code);setCategory('');setStock('all');setQuery(code);setSearch(code);setPage(1);toast(t('Barcode detected.'));}}/>}
    {remove&&<Modal title={t('Delete this product?')} onClose={()=>{if(!deleting)setRemove(null);}}><p><strong>{remove.name}</strong> · {remove.code}</p><p className="catalog-help">{t('This removes the product from the active catalog. Existing invoices and stock history are preserved.')}</p><ErrorBox error={deleteError}/><div className="form-actions"><Button variant="secondary" disabled={deleting} onClick={()=>setRemove(null)}>{t('Cancel')}</Button><Button variant="danger-fill" disabled={deleting} onClick={async()=>{setDeleting(true);try{await api('/products/'+remove.id,'DELETE');setRemove(null);reload();toast(t('Record archived. Transaction history preserved.'));}catch(e){setDeleteError(t(e.message));}finally{setDeleting(false);}}}>{t(deleting?'Saving…':'Delete')}</Button></div></Modal>}
  </div>;
}
