import React,{useState} from 'react';
import {Modal,Button,ErrorBox,useApp,api} from '../main.jsx';
import {catalogText} from '../catalog-i18n.js';
export default function StockEditor({product,onClose,onSaved}){
 const {lang,go}=useApp(),t=(s)=>catalogText(s,lang);
 const [mode,setMode]=useState('set'),[quantity,setQuantity]=useState(String(product.quantity)),[reason,setReason]=useState('Opening stock'),[note,setNote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const next=mode==='add'?product.quantity+Number(quantity):mode==='remove'?product.quantity-Number(quantity):Number(quantity),valid=quantity.trim()!==''&&Number.isInteger(next)&&next>=0&&next<=100000&&(mode==='set'||Number(quantity)>0);
 return <Modal title={t('Update stock')} onClose={()=>{if(!busy)onClose();}}><form onSubmit={async e=>{e.preventDefault();setError('');if(!valid){setError(t('Use a whole number from 0 to 100000'));return;}setBusy(true);try{await api('/stock/set','POST',{product_id:product.id,mode,quantity:Number(quantity),expected_quantity:product.quantity,reason:mode==='add'?'Received stock':reason,note:note.trim()});onSaved();onClose();}catch(e){setError(t(e.message));}finally{setBusy(false);}}}>
 <p><strong>{product.name}</strong></p><label className="field"><span>{t('Stock update type')}</span><select disabled={busy} value={mode} onChange={e=>{setMode(e.target.value);setQuantity(e.target.value!=='set'?'':String(product.quantity));}}><option value="set">{t('Set actual quantity')}</option><option value="add">{t('Add stock')}</option><option value="remove">{t('Remove stock')}</option></select></label>
 <p className="catalog-help">{t(mode==='set'?'Enter the total stock currently in your shop, including existing opening stock.':mode==='remove'?'Enter units to remove from current stock.':'Enter extra units for a manual adjustment, not a supplier delivery.')}</p>
 <label className="field"><span>{t(mode==='set'?'Stock quantity':'Quantity to change')}</span><input autoFocus type="number" min={mode==='set'?0:1} max="100000" step="1" required value={quantity} onChange={e=>setQuantity(e.target.value)} disabled={busy}/></label>
 <div className="stock-preview" role="status"><span>{t('Old quantity')}<strong>{product.quantity}</strong></span><span>{t('Change')}<strong>{valid?(next-product.quantity>0?'+':'')+(next-product.quantity):'—'}</strong></span><b aria-hidden="true">→</b><span>{t('New quantity')}<strong>{valid?next:'—'}</strong></span></div>
 {mode==='set'&&<label className="field"><span>{t('Reason for stock change')}</span><select value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}><option value="Opening stock">{t('Opening stock')}</option><option value="Count correction">{t('Count correction')}</option></select></label>}
 <label className="field"><span>{t('Stock change note')}</span><input required maxLength={200} value={note} onChange={e=>setNote(e.target.value)} disabled={busy}/></label><p className="catalog-help">{t('The date, reason, and quantity change will be recorded in stock history.')}</p>
 <p className="catalog-help">{t('Supplier delivery? Record it in Purchases only to avoid counting it twice.')}</p><Button type="button" variant="secondary" disabled={busy} onClick={()=>{onClose();go('Purchases');}}>{t('Receive purchase')}</Button><ErrorBox error={error}/><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={onClose}>{t('Cancel')}</Button><Button disabled={busy||!valid||next===product.quantity}>{t(busy?'Saving…':'Save changes')}</Button></div>
 </form></Modal>;
}
