import fs from 'node:fs';
import pathModule from 'node:path';
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
async function component(path){const result=await build({stdin:{contents:fs.readFileSync(path,"utf8"),loader:"jsx",resolveDir:pathModule.resolve(pathModule.dirname(path))},tsconfigRaw:{},bundle:true,write:false,platform:'node',format:'cjs',external:['react'],plugins:[{name:'shared-ui-test-context',setup(b){b.onResolve({filter:/^\.\.?\//},a=>a.path.endsWith('main.jsx')?null:({path:pathModule.resolve(a.resolveDir,a.path),namespace:'local-source'}));b.onLoad({filter:/.*/,namespace:'local-source'},a=>({contents:fs.readFileSync(a.path,'utf8'),loader:'js',resolveDir:pathModule.dirname(a.path)}));b.onResolve({filter:/main\.jsx$/},()=>({path:'ui-context',namespace:'test'}));b.onLoad({filter:/.*/,namespace:'test'},()=>({loader:'jsx',contents:`import React from 'react';export const useApp=()=>({lang:'en',settings:{currency:'LKR'},user:{role:'admin'},t:s=>s,toast:()=>{},go:()=>{}});export const api=()=>{};export const dateTime=s=>s;export const Money=({value})=><span>LKR {(Number(value)/100).toFixed(2)}</span>;export const Modal=({children,title})=><section aria-label={title}>{children}</section>;export const Button=({children,variant,...p})=><button {...p}>{children}</button>;export const ErrorBox=({error})=>error?<p role="alert">{error}</p>:null;` }));}}]});const m={exports:{}};new Function('require','module','exports',result.outputFiles[0].text)(require,m,m.exports);return m.exports.default;}
test('stock editor renders the shared three modes and before/change/after preview',async()=>{const Stock=await component('src/catalog/StockEditor.jsx');const html=renderToStaticMarkup(React.createElement(Stock,{product:{name:'Pen',id:1,quantity:10},onClose(){},onSaved(){}}));for(const text of ['Set actual quantity','Add stock','Remove stock','Old quantity','New quantity','Change','Supplier delivery?'])assert.ok(html.includes(text),text);});
test('refund workflow renders pending amount, original correction warning and explicit payment confirmation',async()=>{const Workflow=await component('src/TransactionWorkflow.jsx');const html=renderToStaticMarkup(React.createElement(Workflow,{sale:{id:1,status:'Refund Pending',transaction_status:'Voided',refund_due:13000,refunded:0,items:[],corrections:[{id:1,created_at:'2026-09-28',employee:'Owner',reason:'Wrong item',amount:13000,restock:true}],refunds:[]},reload(){}}));for(const text of ['Refund Pending','Voided','LKR 130.00','Record refund','I confirm this money was returned','Wrong item'])assert.ok(html.includes(text),text);});
test('transaction actions offer correction and void only for active invoices',async()=>{const Actions=await component('src/InvoiceActions.jsx');const active=renderToStaticMarkup(React.createElement(Actions,{saleId:1,refundDue:0}));assert.ok(active.includes('Correct invoice item'));assert.ok(active.includes('Void invoice'));assert.ok(!active.includes('Record refund'));const voided=renderToStaticMarkup(React.createElement(Actions,{saleId:1,canCorrect:false,refundDue:13000}));assert.ok(voided.includes('Record refund'));assert.ok(!voided.includes('Void invoice'));});
test('void action opens explicit consequence preview, reason, cancel and confirmation',async()=>{const Workflow=await component('src/TransactionWorkflow.jsx');const html=renderToStaticMarkup(React.createElement(Workflow,{action:'void',sale:{id:1,invoice_number:'TEST-1',total:1000,status:'Completed',transaction_status:'Completed',refund_due:0,refunded:0,items:[{id:2,name:'Pen',quantity:1}],corrections:[],refunds:[]},reload(){}}));for(const text of ['TEST-1','LKR 10.00','LKR 0.00','Original details and payments are preserved','Reason for correction','Cancel','Confirm void'])assert.ok(html.includes(text),text);});
