import fs from 'node:fs/promises';
import path from 'node:path';
import {rows,one,audit} from './db.js';
import {fail} from './domain.js';
export const tables=['users','categories','brands','suppliers','customers','products','sales','sale_items','purchases','purchase_items','payments','expenses','stock_history','settings','audit_logs','sale_corrections','sale_refunds','expense_categories','backup_status','stock_batches'];
export async function snapshot(db){return db.transaction(async tx=>{await tx.query('SET TRANSACTION ISOLATION LEVEL REPEATABLE READ');const data={};for(const table of tables)data[table]=await rows(tx,`SELECT * FROM ${table} ORDER BY id`);return {format:'smart-retail-v1',created_at:new Date().toISOString(),data};});}
export async function saveBackup(db){const dir=path.resolve(process.env.BACKUP_DIR||'./backups');await fs.mkdir(dir,{recursive:true});const name=`smart-retail-${new Date().toISOString().replaceAll(':','-')}.json`;await fs.writeFile(path.join(dir,name),JSON.stringify(await snapshot(db)),{mode:0o600,flag:'wx'});const files=(await fs.readdir(dir)).filter(f=>/^smart-retail-[\dT.Z-]+\.json$/.test(f)).sort().reverse();const keep=Math.max(2,Number(process.env.BACKUP_KEEP)||14);for(const f of files.slice(keep))await fs.unlink(path.join(dir,f));await db.query('UPDATE backup_status SET last_success=NOW(),last_error=NULL WHERE id=1');return name;}
export async function restore(db,backup,user){
 if(backup?.data){backup=structuredClone(backup);for(const t of ['sale_corrections','sale_refunds','expense_categories','backup_status','stock_batches'])backup.data[t]??=[];for(const s of backup.data.sales||[]){s.deleted_at??=null;s.deletion_reason??=null;s.deleted_by??=null;}for(const p of backup.data.products||[])p.tax_mode??=p.tax?'custom':'shop';}

 if(backup?.format!=='smart-retail-v1'||!backup.data||tables.some(t=>!Array.isArray(backup.data[t])))fail('Invalid backup format.');
 if(!backup.data.users.some(u=>u.role==='admin'&&u.active))fail('Backup must contain an active administrator.');
 if(backup.data.settings.length!==1||backup.data.settings[0].id!==1)fail('Backup must include shop settings.');
 const columns={};for(const t of tables)columns[t]=new Set((await rows(db,'SELECT column_name FROM information_schema.columns WHERE table_schema=$1 AND table_name=$2',['public',t])).map(c=>c.column_name));
 for(const t of tables)for(const row of backup.data[t]){if(!row||typeof row!=='object'||Array.isArray(row)||Object.keys(row).some(k=>!columns[t].has(k)))fail('Invalid backup row in '+t);}
 await db.transaction(async tx=>{for(const t of [...tables].reverse())await tx.query(`DELETE FROM ${t}`);for(const t of tables){for(const row of backup.data[t]){const keys=Object.keys(row);await tx.query(`INSERT INTO ${t}(${keys.map(k=>'"'+k+'"').join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')})`,keys.map(k=>typeof row[k]==='object'&&row[k]!==null?JSON.stringify(row[k]):row[k]));}if(!['settings','backup_status'].includes(t))await tx.query(`SELECT setval(pg_get_serial_sequence('${t}','id'),COALESCE((SELECT MAX(id) FROM ${t}),1),(SELECT COUNT(*)>0 FROM ${t}))`);}await tx.query("INSERT INTO sale_corrections(sale_id,item_id,reason,created_by,created_at,amount,tax,cost,quantity) SELECT i.sale_id,i.id,COALESCE(i.removal_reason,'Legacy correction'),(SELECT a.user_id FROM audit_logs a WHERE a.entity='sale' AND a.entity_id=i.sale_id::text AND a.action='remove_item' AND (a.detail->'item'->>'id')=i.id::text ORDER BY a.id LIMIT 1),i.removed_at,i.total,i.tax,i.cost*i.quantity,i.quantity FROM sale_items i WHERE i.removed_at IS NOT NULL ON CONFLICT(item_id) DO NOTHING");await tx.query('INSERT INTO backup_status(id) VALUES(1) ON CONFLICT(id) DO NOTHING');await tx.query('UPDATE users SET session_version=session_version+1');await audit(tx,null,'restore','database','',{requested_by:user.email,backup_date:backup.created_at});});
}
