import {z} from 'zod';
import {one,rows,audit} from './db.js';
import {productSchema,contactSchema,id,text,quantity,money,fail} from './domain.js';
import {hashPassword} from './security.js';
import ExcelJS from 'exceljs';
import {editableProductSchema,resolveProductOptions} from './product-options.js';
export function catalogRoutes(app,db,admin){
 const productQuery=`SELECT p.*,c.name category,b.name brand,s.name supplier FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN brands b ON b.id=p.brand_id LEFT JOIN suppliers s ON s.id=p.supplier_id`;
 app.get('/api/products',async(req,res)=>{const list=await rows(db,productQuery+' WHERE p.active=TRUE ORDER BY p.name');res.json(list.map(p=>{if(req.user.role!=='admin'){delete p.purchase_price;delete p.supplier_id;delete p.supplier;}return p;}));});
 app.post('/api/products',admin,async(req,res)=>{const input=editableProductSchema.parse(req.body);const initial=z.number().int().min(0).max(100000).parse(req.body.quantity||0);const result=await db.transaction(async tx=>{const p=await resolveProductOptions(tx,input,req.user);const keys=Object.keys(p);const r=await one(tx,`INSERT INTO products(${keys.join(',')},quantity) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')},$${keys.length+1}) RETURNING *`,[...Object.values(p),initial]);await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,created_by) VALUES($1,$2,$2,$3,$4)',[r.id,initial,'Opening stock',req.user.id]);await audit(tx,req.user,'create','product',r.id);return r;});res.status(201).json(result);});
 app.put('/api/products/:id',admin,async(req,res)=>{const input=editableProductSchema.parse(req.body);const pid=id.parse(req.params.id);const r=await db.transaction(async tx=>{const old=await one(tx,'SELECT * FROM products WHERE id=$1 AND active=TRUE FOR UPDATE',[pid]);if(!old)fail('Product not found.',404);const p=await resolveProductOptions(tx,input,req.user);const keys=Object.keys(p);const r=await one(tx,`UPDATE products SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')} WHERE id=$${keys.length+1} RETURNING *`,[...Object.values(p),pid]);await audit(tx,req.user,'update','product',pid,{before:old,after:p});return r;});res.json(r);});
 app.delete('/api/products/:id',admin,async(req,res)=>{const pid=id.parse(req.params.id);await db.transaction(async tx=>{const r=await one(tx,'UPDATE products SET active=FALSE WHERE id=$1 AND active=TRUE RETURNING id',[pid]);if(!r)fail('Product not found.',404);await audit(tx,req.user,'archive','product',pid);});res.json({ok:true,archived:true});});
 app.post('/api/stock/set',admin,async(req,res)=>{const input=z.object({product_id:id,quantity:z.number().int().min(0).max(100000),expected_quantity:z.number().int().min(0),mode:z.enum(['set','add','remove']).default('set'),reason:z.enum(['Opening stock','Count correction','Received stock']).default('Count correction'),note:z.string().trim().min(1).max(200)}).parse(req.body);const result=await db.transaction(async tx=>{const p=await one(tx,'SELECT * FROM products WHERE id=$1 AND active=TRUE FOR UPDATE',[input.product_id]);if(!p)fail('Product not found.',404);if(p.quantity!==input.expected_quantity)fail('Stock changed since this page loaded. Close this dialog and refresh before trying again.',409);const next=input.mode==='add'?p.quantity+input.quantity:input.mode==='remove'?p.quantity-input.quantity:input.quantity;if(next<0||next>100000)fail('Use a whole number from 0 to 100000');if(input.mode!=='set'&&input.quantity===0)fail('Received quantity must be greater than zero.');const delta=next-p.quantity;if(!delta)return p;const updated=await one(tx,'UPDATE products SET quantity=$1 WHERE id=$2 RETURNING *',[next,p.id]);await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,reference,created_by) VALUES($1,$2,$3,$4,$5,$6)',[p.id,delta,next,input.mode==='add'?'Manual addition':input.mode==='remove'?'Manual removal':input.reason,input.note,req.user.id]);await audit(tx,req.user,'adjust','stock',p.id,{...input,delta});return updated;});res.json(result);});
 app.post('/api/stock/adjust',admin,async(req,res)=>{const input=z.object({product_id:id,delta:z.number().int().min(-100000).max(100000).refine(n=>n!==0),reason:z.enum(['Damaged','Count correction','Opening stock']),note:text}).parse(req.body);const p=await db.transaction(async tx=>{const p=await one(tx,'SELECT * FROM products WHERE id=$1 AND active=TRUE FOR UPDATE',[input.product_id]);if(!p)fail('Product not found.',404);if(input.reason==='Damaged'&&input.delta>0)fail('Damaged stock must reduce the quantity.');if(p.quantity+input.delta<0)fail('Stock cannot be negative.');const updated=await one(tx,'UPDATE products SET quantity=quantity+$1 WHERE id=$2 RETURNING *',[input.delta,p.id]);await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,reference,created_by) VALUES($1,$2,$3,$4,$5,$6)',[p.id,input.delta,updated.quantity,input.reason,input.note,req.user.id]);await audit(tx,req.user,'adjust','stock',p.id,input);return updated;});res.json(p);});
 app.get('/api/stock/history',admin,async(req,res)=>res.json(await rows(db,'SELECT h.*,p.name product,u.name employee FROM stock_history h JOIN products p ON p.id=h.product_id JOIN users u ON u.id=h.created_by ORDER BY h.id DESC LIMIT 2000')));
 for(const table of ['categories','brands','customers','suppliers']){
  const schema=['categories','brands'].includes(table)?z.object({name:text}):table==='suppliers'?contactSchema.extend({company:z.string().max(200).default('')}):contactSchema;
  app.get('/api/'+table,...(table==='suppliers'?[admin]:[]),async(req,res)=>{let list=await rows(db,`SELECT * FROM ${table} ${['customers','suppliers'].includes(table)?'WHERE active=TRUE':''} ORDER BY name`);if(table==='customers'&&req.user.role==='admin')list=await rows(db,`SELECT c.*,COALESCE(SUM(s.total),0)::bigint total_purchases,COALESCE(SUM(s.outstanding),0)::bigint credit_balance FROM customers c LEFT JOIN sales_state s ON s.customer_id=c.id AND s.deleted_at IS NULL WHERE c.active=TRUE GROUP BY c.id ORDER BY c.name`);if(table==='suppliers')list=await rows(db,'SELECT s.*,(SELECT COALESCE(SUM(total-paid),0) FROM purchases p WHERE p.supplier_id=s.id)::bigint balance FROM suppliers s WHERE active=TRUE ORDER BY s.name');res.json(list);});
  app.post('/api/'+table,admin,async(req,res)=>{const p=schema.parse(req.body),keys=Object.keys(p);const r=await db.transaction(async tx=>{const r=await one(tx,`INSERT INTO ${table}(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING *`,Object.values(p));await audit(tx,req.user,'create',table,r.id);return r;});res.status(201).json(r);});
  app.put('/api/'+table+'/:id',admin,async(req,res)=>{const p=schema.parse(req.body),keys=Object.keys(p),pid=id.parse(req.params.id);const r=await db.transaction(async tx=>{const r=await one(tx,`UPDATE ${table} SET ${keys.map((k,i)=>`${k}=$${i+1}`).join(',')} WHERE id=$${keys.length+1} RETURNING *`,[...Object.values(p),pid]);if(!r)fail('Record not found.',404);await audit(tx,req.user,'update',table,pid);return r;});res.json(r);});
  app.delete('/api/'+table+'/:id',admin,async(req,res)=>{const pid=id.parse(req.params.id);const archived=await db.transaction(async tx=>{const old=await one(tx,`SELECT * FROM ${table} WHERE id=$1 FOR UPDATE`,[pid]);if(!old||old.active===false)fail('Record not found.',404);const linked=table==='customers'?await one(tx,'SELECT id FROM sales WHERE customer_id=$1 LIMIT 1',[pid]):table==='suppliers'?await one(tx,'SELECT id FROM purchases WHERE supplier_id=$1 UNION ALL SELECT id FROM products WHERE supplier_id=$1 LIMIT 1',[pid]):null;if(linked){await tx.query(`UPDATE ${table} SET active=FALSE WHERE id=$1`,[pid]);}else{await tx.query(`DELETE FROM ${table} WHERE id=$1`,[pid]);}await audit(tx,req.user,linked?'archive':'delete',table,pid);return !!linked;});res.json({ok:true,archived});});
 }
 app.get('/api/customers/:id/statement',admin,async(req,res)=>{const cid=id.parse(req.params.id);const customer=await one(db,'SELECT * FROM customers WHERE id=$1',[cid]);if(!customer)fail('Customer not found.',404);res.json({customer,sales:await rows(db,'SELECT id,invoice_number,total,paid,created_at,method,status,refunded,refund_due,outstanding FROM sales_state WHERE customer_id=$1 AND deleted_at IS NULL ORDER BY id DESC',[cid]),payments:await rows(db,'SELECT p.*,s.invoice_number FROM payments p JOIN sales s ON s.id=p.sale_id WHERE s.customer_id=$1 AND s.deleted_at IS NULL ORDER BY p.id DESC',[cid])});});
 app.get('/api/users',admin,async(req,res)=>res.json(await rows(db,'SELECT id,name,email,role,active,phone,address,created_at FROM users ORDER BY name')));
 const userSchema=z.object({name:text,email:z.string().email().max(200).transform(s=>s.toLowerCase()),role:z.enum(['admin','cashier']),active:z.boolean().default(true),phone:z.string().max(100).default(''),address:z.string().max(1000).default(''),password:z.string().min(12).max(128).optional()});
 app.post('/api/users',admin,async(req,res)=>{const u=userSchema.parse(req.body);if(!u.password)fail('Password must contain at least 12 characters.');const hash=await hashPassword(u.password);const r=await db.transaction(async tx=>{const r=await one(tx,'INSERT INTO users(name,email,role,active,phone,address,password_hash) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,name,email,role,active',[u.name,u.email,u.role,u.active,u.phone,u.address,hash]);await audit(tx,req.user,'create','user',r.id);return r;});res.status(201).json(r);});
 app.put('/api/users/:id',admin,async(req,res)=>{const uid=id.parse(req.params.id),u=userSchema.parse(req.body);if(uid===req.user.id&&(!u.active||u.role!=='admin'))fail('You cannot disable or demote your own administrator account.');await db.transaction(async tx=>{const r=await one(tx,'UPDATE users SET name=$1,email=$2,role=$3,active=$4,phone=$5,address=$6,session_version=session_version+1 WHERE id=$7 RETURNING id',[u.name,u.email,u.role,u.active,u.phone,u.address,uid]);if(!r)fail('User not found.',404);if(u.password)await tx.query('UPDATE users SET password_hash=$1 WHERE id=$2',[await hashPassword(u.password),uid]);await audit(tx,req.user,'update','user',uid,{role:u.role,active:u.active,password_reset:!!u.password});});res.json({ok:true});});
 app.get('/api/products/export.xlsx',admin,async(req,res)=>{const book=new ExcelJS.Workbook(),sheet=book.addWorksheet('Products');const list=await rows(db,'SELECT * FROM products WHERE active=TRUE ORDER BY id');const columns=['name','code','barcode','category_id','brand_id','supplier_id','purchase_price','selling_price','discount','tax','tax_mode','quantity','min_stock','unit','description'];sheet.columns=columns.map(key=>({header:key,key,width:22}));list.forEach(p=>sheet.addRow({...p,purchase_price:p.purchase_price/100,selling_price:p.selling_price/100,discount:p.discount/100,tax:p.tax/100}));sheet.getRow(1).font={bold:true};res.type('application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');res.attachment('products.xlsx');await book.xlsx.write(res);res.end();});
 app.post('/api/products/import',admin,async(req,res)=>{const input=z.object({rows:z.array(productSchema.extend({quantity:z.number().int().min(0).max(100000).default(0)})).min(1).max(2000)}).parse(req.body);await db.transaction(async tx=>{for(const p of input.rows){p.tax_mode??=p.tax?'custom':'shop';const keys=Object.keys(p);const r=await one(tx,`INSERT INTO products(${keys.join(',')}) VALUES(${keys.map((_,i)=>'$'+(i+1)).join(',')}) RETURNING id`,Object.values(p));await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,created_by) VALUES($1,$2,$2,$3,$4)',[r.id,p.quantity,'Excel import',req.user.id]);}await audit(tx,req.user,'import','products','',{count:input.rows.length});});res.json({count:input.rows.length});});
}
