import {removeSaleItem} from './reliability.js';
import crypto from 'node:crypto';
import {z} from 'zod';
import {one,rows,audit} from './db.js';
import {id,money,quantity,text,calculateSale,fail} from './domain.js';
export function commerceRoutes(app,db,admin){
 app.post('/api/sales',async(req,res)=>{
  const input=z.object({request_id:z.string().uuid(),customer_id:id.nullable(),items:z.array(z.object({product_id:id,quantity})).min(1).max(200),discount:z.number().int().min(0).max(10000),method:z.enum(['cash','card','credit']),tendered:money}).parse(req.body);
  if(new Set(input.items.map(i=>i.product_id)).size!==input.items.length)fail('Duplicate product lines are not allowed.');
  const result=await db.transaction(async tx=>{
   await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',[input.request_id]);
   // Lock products in a stable order to serialize competing checkouts and avoid deadlocks.
   const products=[];for(const item of [...input.items].sort((a,b)=>a.product_id-b.product_id))products.push(await one(tx,'SELECT * FROM products WHERE id=$1 FOR UPDATE',[item.product_id]));
   const previous=await one(tx,'SELECT id,cashier_id FROM sales WHERE request_id=$1',[input.request_id]);if(previous){if(previous.cashier_id!==req.user.id)fail('Request ID is already in use.',409);return previous;}
   const settings=(await one(tx,'SELECT value FROM settings WHERE id=1')).value;
   if(req.user.role==='cashier'&&input.discount>settings.cashier_discount_limit)fail('Discount exceeds your cashier permission.',403);
   const customer=input.customer_id?await one(tx,'SELECT * FROM customers WHERE id=$1 AND active=TRUE FOR SHARE',[input.customer_id]):null;
   if(input.customer_id&&!customer)fail('Customer not found.');if(input.method==='credit'&&!customer)fail('Choose a customer for credit sales.');
   const total=calculateSale(products,input,settings);
   if(input.method==='cash'&&input.tendered<total.total)fail('Cash received is less than the total.');
   if(input.method==='credit'&&input.tendered>total.total)fail('Credit deposit exceeds the invoice total.');
   const paid=input.method==='credit'?input.tendered:total.total;
   const number='SR-'+new Date().toISOString().slice(0,10).replaceAll('-','')+'-'+crypto.randomBytes(5).toString('hex').toUpperCase();
   const sale=await one(tx,`INSERT INTO sales(invoice_number,request_id,customer_id,cashier_id,subtotal,discount,tax,total,cost,paid,tendered,method,shop_snapshot,customer_snapshot,cashier_name) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15) RETURNING id`,[number,input.request_id,input.customer_id,req.user.id,total.subtotal,total.discount,total.tax,total.total,total.cost,paid,input.method==='card'?total.total:input.tendered,input.method,JSON.stringify(settings),JSON.stringify(customer),req.user.name]);
   for(const line of total.lines){const keys=Object.keys(line);await tx.query(`INSERT INTO sale_items(sale_id,${keys.join(',')}) VALUES($1,${keys.map((_,i)=>'$'+(i+2)).join(',')})`,[sale.id,...Object.values(line)]);const p=await one(tx,'UPDATE products SET quantity=quantity-$1 WHERE id=$2 RETURNING quantity',[line.quantity,line.product_id]);await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,reference,created_by) VALUES($1,$2,$3,$4,$5,$6)',[line.product_id,-line.quantity,p.quantity,'Sale',number,req.user.id]);}
   if(paid>0)await tx.query('INSERT INTO payments(sale_id,amount,method,created_by,reference) VALUES($1,$2,$3,$4,$5)',[sale.id,paid,input.method==='card'?'card':'cash',req.user.id,'Initial payment']);
   await audit(tx,req.user,'create','sale',sale.id,{invoice_number:number,total:total.total});return sale;
  });res.status(201).json({id:result.id});
 });
 app.get('/api/sale-corrections',admin,async(req,res)=>{const input=z.object({product_id:id.optional(),sale_id:id.optional(),from:z.string().date().optional(),to:z.string().date().optional()}).parse(req.query);if(!input.product_id&&!input.sale_id)fail('Choose an invoice or product.');const args=[],where=['i.removed_at IS NULL','s.deleted_at IS NULL'];if(input.product_id){args.push(input.product_id);where.push('i.product_id=$'+args.length);}if(input.sale_id){args.push(input.sale_id);where.push('s.id=$'+args.length);}if(input.from&&input.to){const settings=(await one(db,'SELECT value FROM settings WHERE id=1')).value;args.push(input.from,input.to,settings.timezone);where.push('(s.created_at AT TIME ZONE $'+args.length+')::date BETWEEN $'+(args.length-2)+'::date AND $'+(args.length-1)+'::date');}res.json(await rows(db,'SELECT i.id,i.sale_id,i.name,i.quantity,i.total,s.invoice_number,s.created_at,s.total invoice_total,s.paid,s.refund_due FROM sale_items i JOIN sales_state s ON s.id=i.sale_id WHERE '+where.join(' AND ')+' ORDER BY s.id DESC,i.id',args));});
 app.get('/api/sales',async(req,res)=>{const q=z.object({from:z.string().date().optional(),to:z.string().date().optional(),status:z.enum(['Completed','Voided','Partially Refunded','Refund Pending','Refunded']).optional(),customer_id:id.optional(),cashier_id:id.optional(),method:z.enum(['cash','card','credit']).optional(),deleted:z.enum(['true']).optional()}).parse(req.query),args=[],where=[req.user.role==='admin'&&req.query.deleted==='true'?'s.deleted_at IS NOT NULL':'s.deleted_at IS NULL'];const add=(clause,value)=>{args.push(value);where.push(clause.replace('?', '$'+args.length));};if(req.user.role==='cashier')add('s.cashier_id=?',req.user.id);if(q.cashier_id)add('s.cashier_id=?',q.cashier_id);if(q.customer_id)add('s.customer_id=?',q.customer_id);if(q.method)add('s.method=?',q.method);if(q.status)add(q.status==='Voided'?'s.transaction_status=?':'s.status=?',q.status);if(q.from||q.to){const zone=(await one(db,'SELECT value FROM settings WHERE id=1')).value.timezone;args.push(zone);const expr='(s.created_at AT TIME ZONE $'+args.length+')::date';if(q.from)add(expr+'>=?::date',q.from);if(q.to)add(expr+'<=?::date',q.to);}res.json(await rows(db,'SELECT s.id,s.invoice_number,s.customer_id,s.created_at,s.total,s.paid,s.method,s.cashier_name,s.cashier_id,s.status,s.transaction_status,s.refunded,s.refund_due,s.outstanding,s.deleted_at,s.deletion_reason,c.name customer FROM sales_state s LEFT JOIN customers c ON c.id=s.customer_id '+(where.length?'WHERE '+where.join(' AND '):'')+' ORDER BY s.id DESC LIMIT 2000',args));});
 app.post('/api/sales/:id/items/:itemId/remove',admin,(req,res)=>removeSaleItem(db,req,res));
 app.get('/api/sales/:id',async(req,res)=>res.json(await getInvoice(db,req)));
 app.post('/api/sales/:id/payments',admin,async(req,res)=>{const sid=id.parse(req.params.id),input=paymentSchema.parse(req.body);await db.transaction(async tx=>{const sale=await one(tx,'SELECT * FROM sales WHERE id=$1 FOR UPDATE',[sid]);if(!sale)fail('Invoice not found.',404);if(sale.deleted_at)fail('Invoice was deleted.',409);if(input.amount>sale.total-sale.paid+Number((await one(tx,'SELECT COALESCE(SUM(amount),0) amount FROM sale_refunds WHERE sale_id=$1',[sid])).amount))fail('Payment exceeds outstanding balance.');await tx.query('UPDATE sales SET paid=paid+$1 WHERE id=$2',[input.amount,sid]);await tx.query('INSERT INTO payments(sale_id,amount,method,reference,created_by) VALUES($1,$2,$3,$4,$5)',[sid,input.amount,input.method,input.reference,req.user.id]);await audit(tx,req.user,'payment','sale',sid,input);});res.json({ok:true});});
 app.get('/api/purchases',admin,async(req,res)=>res.json(await rows(db,'SELECT p.*,s.name supplier FROM purchases p JOIN suppliers s ON s.id=p.supplier_id ORDER BY p.id DESC LIMIT 2000')));
 app.get('/api/purchases/:id',admin,async(req,res)=>{const p=await one(db,'SELECT p.*,s.name supplier,s.company,s.phone,s.address FROM purchases p JOIN suppliers s ON s.id=p.supplier_id WHERE p.id=$1',[id.parse(req.params.id)]);if(!p)fail('Purchase not found.',404);res.json({...p,items:await rows(db,'SELECT i.*,p.name FROM purchase_items i JOIN products p ON p.id=i.product_id WHERE purchase_id=$1',[p.id]),payments:await rows(db,'SELECT * FROM payments WHERE purchase_id=$1 ORDER BY id',[p.id])});});
 app.post('/api/purchases',admin,async(req,res)=>{const p=z.object({supplier_id:id,reference:text,request_id:z.string().uuid().optional(),paid:money,items:z.array(z.object({product_id:id,quantity,cost:money})).min(1).max(200)}).parse(req.body);if(new Set(p.items.map(i=>i.product_id)).size!==p.items.length)fail('Merge duplicate purchase lines.');const total=p.items.reduce((s,i)=>s+i.quantity*i.cost,0);if(total>2000000000||p.paid>total)fail('Invalid purchase total or payment.');const result=await db.transaction(async tx=>{if(p.request_id){await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',[p.request_id]);const prior=await one(tx,'SELECT * FROM purchases WHERE request_id=$1',[p.request_id]);if(prior)return prior;}for(const i of [...p.items].sort((a,b)=>a.product_id-b.product_id)){const found=await one(tx,'SELECT id FROM products WHERE id=$1 AND active=TRUE FOR UPDATE',[i.product_id]);if(!found)fail('Product not found.');}if(!await one(tx,'SELECT id FROM suppliers WHERE id=$1 AND active=TRUE FOR SHARE',[p.supplier_id]))fail('Supplier not found.');const r=await one(tx,'INSERT INTO purchases(supplier_id,reference,total,paid,created_by,request_id) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[p.supplier_id,p.reference,total,p.paid,req.user.id,p.request_id||null]);for(const i of p.items){await tx.query('INSERT INTO purchase_items(purchase_id,product_id,quantity,cost) VALUES($1,$2,$3,$4)',[r.id,i.product_id,i.quantity,i.cost]);const updated=await one(tx,'UPDATE products SET quantity=quantity+$1,purchase_price=$2,supplier_id=$3 WHERE id=$4 RETURNING quantity',[i.quantity,i.cost,p.supplier_id,i.product_id]);await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,reference,created_by) VALUES($1,$2,$3,$4,$5,$6)',[i.product_id,i.quantity,updated.quantity,'Purchase',p.reference,req.user.id]);}if(p.paid)await tx.query('INSERT INTO payments(purchase_id,amount,method,created_by) VALUES($1,$2,$3,$4)',[r.id,p.paid,'cash',req.user.id]);await audit(tx,req.user,'create','purchase',r.id);return r;});res.status(201).json(result);});
 app.post('/api/purchases/:id/payments',admin,async(req,res)=>{const pid=id.parse(req.params.id),input=paymentSchema.parse(req.body);await db.transaction(async tx=>{const p=await one(tx,'SELECT * FROM purchases WHERE id=$1 FOR UPDATE',[pid]);if(!p)fail('Purchase not found.',404);if(input.amount>p.total-p.paid)fail('Payment exceeds outstanding balance.');await tx.query('UPDATE purchases SET paid=paid+$1 WHERE id=$2',[input.amount,pid]);await tx.query('INSERT INTO payments(purchase_id,amount,method,reference,created_by) VALUES($1,$2,$3,$4,$5)',[pid,input.amount,input.method,input.reference,req.user.id]);await audit(tx,req.user,'payment','purchase',pid,input);});res.json({ok:true});});
 app.delete('/api/expenses/:id',admin,async(req,res)=>{const eid=id.parse(req.params.id);await db.transaction(async tx=>{const old=await one(tx,'DELETE FROM expenses WHERE id=$1 RETURNING *',[eid]);if(!old)fail('Record not found.',404);await audit(tx,req.user,'delete','expense',eid,{before:old});});res.json({ok:true,archived:false});});
 app.get('/api/expenses',admin,async(req,res)=>res.json(await rows(db,'SELECT e.*,u.name employee FROM expenses e JOIN users u ON u.id=e.created_by ORDER BY date DESC,id DESC LIMIT 2000')));
 app.post('/api/expenses',admin,async(req,res)=>{const p=z.object({category:z.string().trim().min(1).max(100),description:z.string().max(1000),amount:money.refine(n=>n>0),date:z.string().date(),receipt:z.string().max(500000).refine(v=>!v||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v)).default('')}).parse(req.body);if(!await one(db,'SELECT id FROM expense_categories WHERE name=$1',[p.category]))fail('Choose an expense category.');const r=await db.transaction(async tx=>{const r=await one(tx,'INSERT INTO expenses(category,description,amount,date,created_by,receipt) VALUES($1,$2,$3,$4,$5,$6) RETURNING *',[p.category,p.description,p.amount,p.date,req.user.id,p.receipt]);await audit(tx,req.user,'create','expense',r.id);return r;});res.status(201).json(r);});
 app.put('/api/expenses/:id',admin,async(req,res)=>{const p=z.object({category:z.string().trim().min(1).max(100),description:z.string().max(1000),amount:money.refine(n=>n>0),date:z.string().date(),receipt:z.string().max(500000).refine(v=>!v||/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(v)).default('')}).parse(req.body);if(!await one(db,'SELECT id FROM expense_categories WHERE name=$1',[p.category]))fail('Choose an expense category.');const r=await db.transaction(async tx=>{const eid=id.parse(req.params.id),old=await one(tx,'SELECT * FROM expenses WHERE id=$1 FOR UPDATE',[eid]);if(!old)fail('Record not found.',404);const updated=await one(tx,'UPDATE expenses SET category=$1,description=$2,amount=$3,date=$4,receipt=$5 WHERE id=$6 RETURNING *',[p.category,p.description,p.amount,p.date,p.receipt,eid]);await audit(tx,req.user,'update','expense',eid,{before:old,after:updated});return updated;});res.json(r);});
}
const paymentSchema=z.object({amount:money.refine(n=>n>0),method:z.enum(['cash','card','bank']),reference:z.string().max(200).default('')});
export async function getInvoice(db,req){const sale=await one(db,'SELECT * FROM sales_state WHERE id=$1',[id.parse(req.params.id)]);if(!sale)fail('Invoice not found.',404);if(req.user.role!=='admin'&&sale.cashier_id!==req.user.id)fail('This invoice belongs to another cashier.',403);const items=await rows(db,'SELECT * FROM sale_items WHERE sale_id=$1 AND removed_at IS NULL ORDER BY id',[sale.id]);delete sale.cost;for(const i of items)delete i.cost;const originalItems=await rows(db,'SELECT id,name,code,quantity,price,discount,tax,total,removed_at FROM sale_items WHERE sale_id=$1 ORDER BY id',[sale.id]);return {...sale,items,original_items:originalItems,original_total:originalItems.reduce((n,i)=>n+i.total,0),corrections:await rows(db,'SELECT c.id,c.sale_id,c.item_id,c.reason,c.created_by,c.created_at,c.amount,c.tax,c.quantity,c.restock,u.name employee FROM sale_corrections c LEFT JOIN users u ON u.id=c.created_by WHERE sale_id=$1 ORDER BY c.id',[sale.id]),refunds:await rows(db,'SELECT r.*,u.name employee FROM sale_refunds r JOIN users u ON u.id=r.created_by WHERE sale_id=$1 ORDER BY r.id',[sale.id]),payments:await rows(db,'SELECT amount,method,reference,created_at FROM payments WHERE sale_id=$1 ORDER BY id',[sale.id])};}
