import {z} from 'zod';
import {one,rows,audit} from './db.js';
import {fail} from './domain.js';
export function openingStockRoutes(app,db,admin){
 app.post('/api/stock/opening/preview',admin,async(req,res)=>{
 const input=z.object({rows:z.array(z.object({code:z.string().max(60),quantity:z.union([z.string(),z.number()]),note:z.string().max(200).default('')})).min(1).max(500)}).parse(req.body);const seen=new Set();const preview=[];
 for(const [index,row] of input.rows.entries()){const p=await one(db,'SELECT id,code,name,quantity FROM products WHERE code=$1 AND active=TRUE',[row.code.trim()]);const issues=[];const quantity=Number(row.quantity);if(!p)issues.push('Unknown SKU');if(seen.has(row.code.trim()))issues.push('Duplicate SKU');seen.add(row.code.trim());if(String(row.quantity).trim()===''||!Number.isInteger(quantity)||quantity<0||quantity>100000)issues.push('Use a whole number from 0 to 100000');if(!row.note.trim())issues.push('Reason is required');preview.push({row:index+2,...row,quantity,product_id:p?.id,name:p?.name,expected_quantity:p?.quantity,issues});}res.json({rows:preview,valid:preview.every(r=>!r.issues.length)});
 });
 app.post('/api/stock/opening',admin,async(req,res)=>{const input=z.object({request_id:z.string().uuid(),rows:z.array(z.object({product_id:z.number().int().positive(),quantity:z.number().int().min(0).max(100000),expected_quantity:z.number().int().min(0),note:z.string().trim().min(1).max(200)})).min(1).max(500)}).parse(req.body);if(new Set(input.rows.map(r=>r.product_id)).size!==input.rows.length)fail('Duplicate SKU');await db.transaction(async tx=>{await tx.query('SELECT pg_advisory_xact_lock(hashtext($1))',[input.request_id]);if(await one(tx,'SELECT id FROM stock_batches WHERE request_id=$1',[input.request_id]))return;for(const r of [...input.rows].sort((a,b)=>a.product_id-b.product_id)){const p=await one(tx,'SELECT * FROM products WHERE id=$1 AND active=TRUE FOR UPDATE',[r.product_id]);if(!p||p.quantity!==r.expected_quantity)fail('Stock changed. Preview the workbook again.',409);const delta=r.quantity-p.quantity;if(delta){await tx.query('UPDATE products SET quantity=$1 WHERE id=$2',[r.quantity,p.id]);await tx.query('INSERT INTO stock_history(product_id,delta,balance,reason,reference,created_by) VALUES($1,$2,$3,$4,$5,$6)',[p.id,delta,r.quantity,'Opening stock',r.note,req.user.id]);}}await tx.query('INSERT INTO stock_batches(request_id,created_by) VALUES($1,$2)',[input.request_id,req.user.id]);await audit(tx,req.user,'opening_import','stock','',{count:input.rows.length});});res.json({ok:true,count:input.rows.length});});
}
