import {z} from 'zod';
import PDFDocument from 'pdfkit';
import {one,rows} from './db.js';
import {getInvoice} from './commerce.js';
import {reportWorkbook,reportPdf} from './report-export.js';
export async function report(db,query={}){
 const settings=(await one(db,'SELECT value FROM settings WHERE id=1')).value;
 const today=new Intl.DateTimeFormat('en-CA',{timeZone:settings.timezone}).format(new Date());
 const {from,to}=z.object({from:z.string().date(),to:z.string().date()}).parse({from:query.from||today.slice(0,8)+'01',to:query.to||today});
 if(from>to)throw Object.assign(new Error('Start date must be before end date.'),{status:400});
 const args=[from,to,settings.timezone],where="(created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date";
 const summary=await one(db,`SELECT COUNT(*) FILTER(WHERE transaction_status='Completed')::integer transactions,COUNT(*) FILTER(WHERE transaction_status='Voided')::integer voided_transactions,COALESCE(SUM(total),0)::bigint sales,COALESCE(SUM(total-tax-cost),0)::bigint gross_profit,COALESCE(SUM(outstanding),0)::bigint outstanding FROM sales_state WHERE deleted_at IS NULL AND ${where}`,args);
 const flows=await one(db,`SELECT (SELECT COALESCE(SUM(p.amount),0) FROM payments p JOIN sales s ON s.id=p.sale_id WHERE s.deleted_at IS NULL AND (p.created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date)::bigint money_collected,(SELECT COALESCE(SUM(r.amount),0) FROM sale_refunds r JOIN sales s ON s.id=r.sale_id WHERE s.deleted_at IS NULL AND (r.created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date)::bigint refunds,(SELECT COALESCE(SUM(c.amount),0) FROM sale_corrections c JOIN sales s ON s.id=c.sale_id WHERE s.deleted_at IS NULL AND (c.created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date)::bigint corrections,(SELECT COALESCE(SUM(refund_due),0) FROM sales_state WHERE deleted_at IS NULL)::bigint refund_pending`,args);
 const historical=await one(db,`SELECT COALESCE(SUM(i.total),0)::bigint original_sales,COALESCE(SUM(i.cost*i.quantity) FILTER(WHERE i.removed_at IS NULL OR EXISTS(SELECT 1 FROM sale_corrections c WHERE c.item_id=i.id AND c.restock=FALSE)),0)::bigint cost_of_goods FROM sale_items i JOIN sales s ON s.id=i.sale_id WHERE s.deleted_at IS NULL AND (s.created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date`,args);
 const expense=await one(db,'SELECT COALESCE(SUM(amount),0)::bigint expenses FROM expenses WHERE date BETWEEN $1::date AND $2::date',[from,to]);
 const daily=await rows(db,`SELECT (created_at AT TIME ZONE $3)::date::text date,SUM(total)::bigint sales,SUM(total-tax-cost)::bigint profit,COUNT(*)::integer transactions FROM sales WHERE deleted_at IS NULL AND ${where} GROUP BY 1 ORDER BY 1`,args);
 const expenses=await rows(db,'SELECT category,SUM(amount)::bigint amount FROM expenses WHERE date BETWEEN $1::date AND $2::date GROUP BY category ORDER BY SUM(amount) DESC',[from,to]);
 const best=await rows(db,`SELECT i.product_id,i.name,SUM(i.quantity)::integer quantity,SUM(i.total)::bigint revenue,SUM(i.total-i.tax-i.cost*i.quantity)::bigint profit FROM sale_items i JOIN sales s ON s.id=i.sale_id WHERE s.deleted_at IS NULL AND i.removed_at IS NULL AND (s.created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date GROUP BY i.product_id,i.name ORDER BY SUM(i.quantity) DESC`,args);
 const low=await rows(db,'SELECT id,name,code,quantity,min_stock FROM products WHERE active=TRUE AND quantity<=min_stock ORDER BY quantity,name');
 const counts=await one(db,'SELECT (SELECT COUNT(*) FROM products WHERE active=TRUE)::integer products,(SELECT COUNT(*) FROM customers WHERE active=TRUE)::integer customers,(SELECT COUNT(*) FROM suppliers WHERE active=TRUE)::integer suppliers');
 const todays=await one(db,'SELECT COALESCE(SUM(total),0)::bigint total FROM sales WHERE deleted_at IS NULL AND (created_at AT TIME ZONE $2)::date=$1::date',[today,settings.timezone]);
 return {from,to,today:today,settings,summary:{...summary,...flows,...historical,net_collected:Number(flows.money_collected)-Number(flows.refunds),expenses:expense.expenses,net_profit:Number(summary.gross_profit)-Number(expense.expenses),today_sales:todays.total,...counts},daily,expenses,best,low};
}
const cash=(n,currency='LKR')=>`${currency} ${(Number(n)/100).toFixed(2)}`;
export function reportRoutes(app,db,admin){
 app.get('/api/reports',admin,async(req,res)=>res.json(await report(db,req.query)));
 app.get('/api/reports/export.xlsx',admin,async(req,res)=>{const r=await report(db,req.query);const stock=await rows(db,'SELECT name,code,quantity,min_stock,purchase_price,selling_price FROM products WHERE active=TRUE ORDER BY name');const movements=await rows(db,`SELECT h.*,p.name FROM stock_history h JOIN products p ON p.id=h.product_id WHERE (h.created_at AT TIME ZONE $3)::date BETWEEN $1::date AND $2::date AND NOT EXISTS(SELECT 1 FROM sales s WHERE s.deleted_at IS NOT NULL AND s.invoice_number=h.reference AND h.reason IN ('Sale','Invoice correction','Incorrect invoice deleted')) ORDER BY h.id`,[r.from,r.to,r.settings.timezone]);const book=await reportWorkbook(r,{stock,movements});res.attachment('retail-report-'+r.from+'-to-'+r.to+'.xlsx');await book.xlsx.write(res);res.end();});
 app.get('/api/reports/export.pdf',admin,async(req,res)=>{const r=await report(db,req.query);res.type('application/pdf');res.attachment('retail-report-'+r.from+'-to-'+r.to+'.pdf');reportPdf(r,res);});
 app.get('/api/sales/:id/pdf',async(req,res)=>{const sale=await getInvoice(db,req),s=sale.shop_snapshot,doc=new PDFDocument({margin:40,size:'A4'});res.type('application/pdf');res.attachment(sale.invoice_number+'.pdf');doc.pipe(res);if(s.logo){try{doc.image(Buffer.from(s.logo.split(',')[1],'base64'),{width:55});doc.moveDown();}catch{}}doc.fontSize(22).text(s.name).fontSize(10).text(s.address).text(s.phone).moveDown().fontSize(16).text('INVOICE '+sale.invoice_number).fontSize(10).text(new Date(sale.created_at).toLocaleString('en-GB',{timeZone:s.timezone})).text(`Cashier: ${sale.cashier_name}`).text(`Customer: ${sale.customer_snapshot?.name||'Walk-in customer'}`).text(sale.customer_snapshot?.phone||'').text(sale.customer_snapshot?.address||'').moveDown();doc.text(`Status: ${sale.status} | Transaction: ${sale.transaction_status}`).text(`Original total: ${cash(sale.original_total,s.currency)}`).moveDown();for(const i of sale.original_items){if(doc.y>680)doc.addPage();doc.fontSize(11).text(i.name+(i.removed_at?' [Corrected]':'')).fontSize(10).text(`${i.quantity} x ${cash(i.price,s.currency)}   Discount ${cash(i.discount,s.currency)}   Tax ${cash(i.tax,s.currency)}   ${cash(i.total,s.currency)}`).moveDown(0.5);}doc.moveDown();for(const [name,n] of [['Subtotal',sale.subtotal],['Discount',sale.discount],['Tax',sale.tax],['Total',sale.total],['Paid',sale.paid],['Refunded',Number(sale.refunded)],['Balance due',Number(sale.outstanding)],['Refund / correction due',Number(sale.refund_due)],['Change',Math.max(0,sale.tendered-sale.paid)]])doc.text(`${name}: ${cash(n,s.currency)}`,{align:'right'});doc.moveDown().text(`Payment: ${sale.method}`).text(s.thank_you);doc.end();});
}
