import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

const teal='147D70',dark='102F35',ink='223638',muted='60777A',border='DFE8E7',pale='EEF7F4';
const money=n=>Number(n||0)/100;
const cash=(n,currency='LKR')=>`${currency} ${money(n).toLocaleString('en-LK',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const currencyFormat='"LKR" #,##0.00;[Red]("LKR" #,##0.00)';
const summaryGroups=[
 ['Sales and profit',[['Total sales','sales'],['Gross profit','gross_profit'],['Expenses','expenses'],['Net profit','net_profit']]],
 ['Money and balances',[['Original sales','original_sales'],['Net sales','sales'],['Refunds paid in period','refunds'],['Money collected in period','money_collected'],['Outstanding','outstanding'],['Refund pending','refund_pending'],['Cost of goods','cost_of_goods']]],
];

function styleHeader(row,count){row.height=27;for(let c=1;c<=count;c++){const cell=row.getCell(c);cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+dark}};cell.font={name:'Aptos',bold:true,color:{argb:'FFFFFFFF'},size:11};cell.alignment={vertical:'middle'};cell.border={bottom:{style:'thin',color:{argb:'FF'+teal}}};}}
function styleBody(row,count,index){row.height=24;for(let c=1;c<=count;c++){const cell=row.getCell(c);cell.font={name:'Aptos',size:11,color:{argb:'FF'+ink}};cell.alignment={vertical:'middle'};if(index%2===0)cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+pale}};cell.border={bottom:{style:'hair',color:{argb:'FF'+border}}};}}
function sheet(book,name,columns,entries,moneyKeys=[]){const ws=book.addWorksheet(name,{views:[{state:'frozen',ySplit:1}],properties:{tabColor:{argb:'FF'+teal}}});ws.columns=columns.map(([header,key,width])=>({header,key,width}));styleHeader(ws.getRow(1),columns.length);for(const [i,data] of entries.entries()){const row=ws.addRow(data);styleBody(row,columns.length,i);for(const key of moneyKeys)row.getCell(key).numFmt=currencyFormat;}ws.autoFilter={from:{row:1,column:1},to:{row:Math.max(1,ws.rowCount),column:columns.length}};ws.pageSetup={paperSize:9,orientation:'landscape',fitToPage:true,fitToWidth:1,fitToHeight:0};return ws;}

export async function reportWorkbook(r,extra={}){
 const book=new ExcelJS.Workbook();book.creator='Smart Retail';book.title=`${r.settings.name} business report`;book.subject=`${r.from} to ${r.to}`;
 const ws=book.addWorksheet('Report overview',{views:[{state:'frozen',ySplit:4}],properties:{tabColor:{argb:'FF'+teal}}});ws.columns=Array.from({length:8},()=>({width:18}));
 ws.mergeCells('A1:H2');let cell=ws.getCell('A1');cell.value=r.settings.name;cell.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+dark}};cell.font={name:'Aptos Display',size:21,bold:true,color:{argb:'FFFFFFFF'}};cell.alignment={vertical:'middle'};ws.getRow(1).height=27;ws.getRow(2).height=13;
 ws.mergeCells('A3:H3');cell=ws.getCell('A3');cell.value=`Business report  |  ${r.from} to ${r.to}  |  ${r.settings.currency}`;cell.font={name:'Aptos',size:12,bold:true,color:{argb:'FF'+teal}};ws.getRow(3).height=28;
 const primary=summaryGroups[0][1];for(let i=0;i<4;i++){const c=1+i*2,[label,key]=primary[i];ws.mergeCells(5,c,5,c+1);ws.mergeCells(6,c,7,c+1);const title=ws.getCell(5,c),value=ws.getCell(6,c);title.value=label;title.font={name:'Aptos',size:10,color:{argb:'FF'+muted}};value.value=money(r.summary[key]);value.numFmt=currencyFormat;value.font={name:'Aptos Display',size:17,bold:true,color:{argb:'FF'+dark}};for(const x of [title,value]){x.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+pale}};x.alignment={vertical:'middle'};x.border={bottom:{style:'thin',color:{argb:'FF'+border}}};}}ws.getRow(5).height=24;ws.getRow(6).height=30;ws.getRow(7).height=13;
 ws.mergeCells('A9:H9');cell=ws.getCell('A9');cell.value='Money and balances';cell.font={name:'Aptos Display',bold:true,size:14,color:{argb:'FF'+dark}};ws.getRow(9).height=27;
 let line=10;for(const [label,key] of summaryGroups[1][1]){ws.mergeCells(line,1,line,4);ws.mergeCells(line,5,line,8);const left=ws.getCell(line,1),right=ws.getCell(line,5);left.value=label;right.value=money(r.summary[key]);right.numFmt=currencyFormat;right.alignment={horizontal:'right'};for(const x of [left,right]){x.font={name:'Aptos',size:11,color:{argb:'FF'+ink}};if(line%2===0)x.fill={type:'pattern',pattern:'solid',fgColor:{argb:'FF'+pale}};}ws.getRow(line++).height=23;}
 ws.mergeCells(line+1,1,line+1,4);ws.getCell(line+1,1).value='Completed transactions';ws.getCell(line+1,5).value=r.summary.transactions;ws.mergeCells(line+1,5,line+1,8);ws.mergeCells(line+2,1,line+2,4);ws.getCell(line+2,1).value='Voided transactions';ws.getCell(line+2,5).value=r.summary.voided_transactions;ws.mergeCells(line+2,5,line+2,8);
 ws.mergeCells(line+4,1,line+5,8);cell=ws.getCell(line+4,1);cell.value='Sales and profit use corrected invoices in this date range. Collections and refunds use their payment dates. Pending refunds and outstanding balances show current amounts.';cell.alignment={wrapText:true,vertical:'middle'};cell.font={name:'Aptos',size:10,color:{argb:'FF'+muted}};
 sheet(book,'Sales by day',[['Date','date',18],['Sales (LKR)','sales',23],['Profit (LKR)','profit',23],['Transactions','transactions',18]],r.daily.map(d=>({date:d.date,sales:money(d.sales),profit:money(d.profit),transactions:d.transactions})),['sales','profit']);
 sheet(book,'Product performance',[['Product','name',42],['Units','quantity',14],['Revenue (LKR)','revenue',22],['Profit (LKR)','profit',22]],r.best.map(p=>({name:p.name,quantity:p.quantity,revenue:money(p.revenue),profit:money(p.profit)})),['revenue','profit']);
 sheet(book,'Where the money went',[['Expense category','category',36],['Amount (LKR)','amount',24]],r.expenses.map(e=>({category:e.category,amount:money(e.amount)})),['amount']);
 sheet(book,'Low stock',[['Product','name',42],['SKU','code',20],['Available','quantity',16],['Minimum','min_stock',16]],r.low.map(p=>({name:p.name,code:p.code,quantity:p.quantity,min_stock:p.min_stock})));
 sheet(book,'Current stock',[['Product','name',42],['SKU','code',20],['Quantity','quantity',16],['Minimum','min_stock',16],['Cost (LKR)','purchase_price',22],['Price (LKR)','selling_price',22]],(extra.stock||[]).map(p=>({...p,purchase_price:money(p.purchase_price),selling_price:money(p.selling_price)})),['purchase_price','selling_price']);
 sheet(book,'Stock movements',[['Date','created_at',28],['Product','name',38],['Change','delta',14],['Balance','balance',14],['Reason','reason',28],['Reference','reference',28]],(extra.movements||[]).map(m=>({created_at:new Date(m.created_at).toLocaleString('en-GB',{timeZone:r.settings.timezone}),name:m.name,delta:m.delta,balance:m.balance,reason:m.reason,reference:m.reference})));
 return book;
}

export function reportPdf(r,stream){
 const doc=new PDFDocument({size:'A4',margin:40,bufferPages:false,info:{Title:`${r.settings.name} business report`,Author:'Smart Retail'}});doc.pipe(stream);let y=0,page=0;const width=515;
 function footer(){doc.font('Helvetica').fontSize(8).fillColor('#'+muted).text(`${r.settings.name}  •  ${r.from} to ${r.to}`,40,788,{width:420});doc.text(String(page),515,788,{width:40,align:'right'});}
 function header(first=false){page++;doc.rect(0,0,595,first?126:67).fill('#'+dark);doc.font('Helvetica-Bold').fontSize(first?21:14).fillColor('white').text(r.settings.name,40,first?27:24,{width:515});if(first){doc.font('Helvetica').fontSize(11).fillColor('#B9D9D2').text('BUSINESS REPORT',40,60);doc.fontSize(10).text(`${r.from} to ${r.to}  •  ${r.settings.currency}`,40,83);}y=first?148:85;}
 function next(){footer();doc.addPage();header();}
 function need(h){if(y+h>780)next();}
 function title(text){need(39);doc.font('Helvetica-Bold').fontSize(14).fillColor('#'+dark).text(text,40,y);y+=26;doc.moveTo(40,y).lineTo(555,y).lineWidth(1).strokeColor('#'+border).stroke();y+=12;}
 function card(label,value,x,cy,cw=121){doc.roundedRect(x,cy,cw,73,7).fill('#'+pale);doc.font('Helvetica').fontSize(9).fillColor('#'+muted).text(label,x+10,cy+10,{width:cw-20});doc.font('Helvetica-Bold').fontSize(15).fillColor('#'+dark).text(value,x+10,cy+35,{width:cw-20,ellipsis:true,lineBreak:false});}
 function table(headings,rows,widths,formatter){const rowHeight=27;const drawHead=()=>{need(30);doc.rect(40,y,width,27).fill('#'+dark);let x=40;headings.forEach((h,i)=>{doc.font('Helvetica-Bold').fontSize(9).fillColor('white').text(h,x+7,y+8,{width:widths[i]-14,ellipsis:true,lineBreak:false});x+=widths[i];});y+=27;};drawHead();if(!rows.length){need(rowHeight);doc.font('Helvetica').fontSize(9).fillColor('#'+muted).text('No records in this period',48,y+8);y+=rowHeight;return;}for(const [index,row] of rows.entries()){if(y+rowHeight>780){next();drawHead();}if(index%2===0)doc.rect(40,y,width,rowHeight).fill('#F6F9F8');let x=40;formatter(row).forEach((v,i)=>{doc.font('Helvetica').fontSize(9).fillColor('#'+ink).text(String(v??''),x+7,y+8,{width:widths[i]-14,ellipsis:true,lineBreak:false,align:i>0&&/^(-?LKR|\d)/.test(String(v))?'right':'left'});x+=widths[i];});y+=rowHeight;}}
 header(true);title('Your business at a glance');const primary=summaryGroups[0][1];primary.forEach(([label,key],i)=>card(label,cash(r.summary[key],r.settings.currency),40+i*131,y));y+=91;
 title('Money and balances');for(const [i,[label,key]] of summaryGroups[1][1].entries()){const col=i%2,row=Math.floor(i/2),x=40+col*262,cy=y+row*54;doc.roundedRect(x,cy,253,47,6).lineWidth(.7).strokeColor('#'+border).stroke();doc.font('Helvetica').fontSize(9).fillColor('#'+muted).text(label,x+9,cy+7,{width:235});doc.font('Helvetica-Bold').fontSize(12).fillColor('#'+dark).text(cash(r.summary[key],r.settings.currency),x+9,cy+23,{width:235});}y+=Math.ceil(summaryGroups[1][1].length/2)*54+13;
 need(47);doc.font('Helvetica').fontSize(9).fillColor('#'+ink).text(`${r.summary.transactions} completed transactions     ${r.summary.voided_transactions} voided transactions`,40,y);y+=20;
 doc.fontSize(8).fillColor('#'+muted).text('Sales and profit use corrected invoices in this date range. Collections and refunds use their payment dates. Pending refunds and outstanding balances are current.',40,y,{width});y+=36;
 title('Sales and profit by day');table(['Date','Sales','Profit','Transactions'],r.daily,[138,137,137,103],d=>[d.date,cash(d.sales,r.settings.currency),cash(d.profit,r.settings.currency),d.transactions]);y+=17;
 title('Product performance');table(['Product','Units','Revenue','Profit'],r.best,[204,60,125,126],p=>[p.name,p.quantity,cash(p.revenue,r.settings.currency),cash(p.profit,r.settings.currency)]);y+=17;
 title('Where the money went');table(['Expense category','Amount'],r.expenses,[310,205],e=>[e.category,cash(e.amount,r.settings.currency)]);footer();doc.end();return doc;
}
