import React,{useEffect,useRef,useState} from 'react';
import {Button,ErrorBox,Money,api,useApp} from './main.jsx';
export default function DeleteInvoice({sale,openInitially=false,onDeleted}){
 const {t,toast}=useApp(),[open,setOpen]=useState(openInitially),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState(''),section=useRef(null),busyLock=useRef(false);
 useEffect(()=>{if(openInitially)section.current?.scrollIntoView?.({block:'start',behavior:'smooth'});},[openInitially]);
 if(sale.deleted_at)return <p className="badge neutral">{t('Deleted incorrect invoice')} · {sale.deletion_reason}</p>;
 const submit=async e=>{e.preventDefault();if(busyLock.current)return;busyLock.current=true;setBusy(true);setError('');try{await api('/sales/'+sale.id,'DELETE',{reason,confirm_no_exchange:confirmed});window.dispatchEvent(new Event('retail-data-changed'));toast(t('Incorrect invoice deleted from reports.'));onDeleted();}catch(e){setError(t(e.message));}finally{setBusy(false);busyLock.current=false;}};
 return <section className="transaction-workflow no-print" ref={section}><Button variant="secondary" onClick={()=>setOpen(true)}>{t('Delete incorrect invoice')}</Button>{open&&<form onSubmit={submit}><h3>{t('Delete incorrect invoice')} · {sale.invoice_number}</h3><p>{t('This removes the invoice from sales, customer balances, and all report totals. Stock is restored. An audit record remains.')}</p><p>{t('Original total')}: <Money value={sale.original_total}/> · {t('Recorded payment')}: <Money value={sale.paid}/></p><label className="field"><span>{t('Reason for deletion')}</span><input required maxLength={200} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="check-label"><input type="checkbox" required checked={confirmed} disabled={busy} onChange={e=>setConfirmed(e.target.checked)}/>{t('I confirm no goods or money changed hands for this incorrect invoice.')}</label><ErrorBox error={error}/><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>{setOpen(false);setReason('');setConfirmed(false);}}>{t('Cancel')}</Button><Button variant="danger-fill" disabled={busy||!confirmed}>{t('Delete invoice')}</Button></div></form>}</section>;
}
