import React,{useEffect,useRef,useState} from 'react';
import {Button,ErrorBox,Money,api,useApp,dateTime} from './main.jsx';
export default function TransactionWorkflow({sale,reload,action,itemId}){
 const {t,user,toast}=useApp(),[item,setItem]=useState(action==='correct'&&itemId?String(itemId):''),[voiding,setVoiding]=useState(action==='void'),[reason,setReason]=useState(''),[restock,setRestock]=useState(true),[amount,setAmount]=useState(''),[method,setMethod]=useState('cash'),[reference,setReference]=useState(''),[paid,setPaid]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState('');const section=useRef(null);useEffect(()=>{if(action&&action!=='view'){section.current?.scrollIntoView?.({block:'start',behavior:'smooth'});section.current?.querySelector('select,input,button')?.focus();}},[action]);const refundRequest=useRef(null),lock=useRef(false);
 const save=async(kind)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');try{if(kind==='void'){await api(`/sales/${sale.id}/void`,'POST',{reason,restock});setVoiding(false);}else if(kind==='correct'){await api(`/sales/${sale.id}/items/${item}/remove`,'POST',{reason,restock});setItem('');}else{refundRequest.current||=crypto.randomUUID();await api(`/sales/${sale.id}/refunds`,'POST',{request_id:refundRequest.current,amount:Math.round(Number(amount)*100),method,reason,reference});refundRequest.current=null;setAmount('');setPaid(false);}await reload();setReason('');toast(t('Transaction updated.'));}catch(e){setError(t(e.message));}finally{setBusy(false);lock.current=false;}};
 return <section ref={section} className="transaction-workflow no-print"><h3>{t('Transaction corrections and refunds')}</h3><p><span className="badge">{t(sale.status)}</span> {sale.transaction_status!==sale.status&&<span className="badge neutral">{t(sale.transaction_status)}</span>}</p><p>{t('Refund pending')}: <Money value={Number(sale.refund_due)}/> · {t('Refunded')}: <Money value={Number(sale.refunded)}/></p>
 {user.role==='admin'&&<><ErrorBox error={error}/>{!voiding&&sale.items.length>0&&<Button variant="secondary" onClick={()=>{setItem('');setVoiding(true);}}>{t('Void invoice')}</Button>}{voiding&&sale.items.length>0&&<form onSubmit={e=>{e.preventDefault();save('void');}}><h4>{t('Void invoice')} · {sale.invoice_number}</h4><p>{t('This reverses all remaining invoice items. Original details and payments are preserved. Record any refund separately.')}</p><p>{t('Net sales')}: <Money value={sale.total}/> → <Money value={0}/></p><label className="field"><span>{t('Reason for correction')}</span><input required maxLength={200} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={restock} disabled={busy} onChange={e=>setRestock(e.target.checked)}/>{t('Return the full item quantity to stock')}</label><div className="form-actions"><Button type="button" variant="secondary" disabled={busy} onClick={()=>setVoiding(false)}>{t('Cancel')}</Button><Button variant="danger-fill" disabled={busy}>{t('Confirm void')}</Button></div></form>}{!voiding&&sale.items.length>0&&<form onSubmit={e=>{e.preventDefault();save('correct');}}><label className="field"><span>{t('Correct invoice item')}</span><select required value={item} disabled={busy} onChange={e=>setItem(e.target.value)}><option value="">{t('Select item')}</option>{sale.items.map(i=><option key={i.id} value={i.id}>{i.name} × {i.quantity}</option>)}</select></label>{item&&<><label className="field"><span>{t('Reason for correction')}</span><input required maxLength={200} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="check-label"><input type="checkbox" checked={restock} onChange={e=>setRestock(e.target.checked)} disabled={busy}/>{t('Return the full item quantity to stock')}</label><p className="catalog-help">{t('Original invoice details are preserved. This reverses the selected line; it does not pay a refund.')}</p><Button variant="danger-fill" disabled={busy}>{t('Confirm correction')}</Button><Button type="button" variant="secondary" disabled={busy} onClick={()=>setItem('')}>{t('Cancel')}</Button></>}</form>}
 {action==='refund'&&Number(sale.refund_due)<=0&&<p role="status">{t('No refund is pending. Correct an invoice item first if the sale is wrong.')}</p>}{Number(sale.refund_due)>0&&!item&&!voiding&&<form onSubmit={e=>{e.preventDefault();save('refund');}}><h4>{t('Record refund')}</h4><div className="form-grid"><label className="field"><span>{t('Amount')}</span><input type="number" min="0.01" step="0.01" max={Number(sale.refund_due)/100} required value={amount} disabled={busy} onChange={e=>{refundRequest.current=null;setAmount(e.target.value);}}/></label><label className="field"><span>{t('Payment method')}</span><select value={method} disabled={busy} onChange={e=>{refundRequest.current=null;setMethod(e.target.value);}}>{['cash','card','bank'].map(m=><option key={m} value={m}>{t(m)}</option>)}</select></label><label className="field"><span>{t('Reason for correction')}</span><input required maxLength={200} value={reason} disabled={busy} onChange={e=>setReason(e.target.value)}/></label><label className="field"><span>{t('Reference')}</span><input maxLength={200} value={reference} disabled={busy} onChange={e=>setReference(e.target.value)}/></label></div><label className="check-label"><input required type="checkbox" checked={paid} disabled={busy} onChange={e=>setPaid(e.target.checked)}/>{t('I confirm this money was returned to the customer. This records the refund only.')}</label><Button disabled={busy||!paid}>{t('Record refund')}</Button></form>}</>}
 <h4>{t('Correction history')}</h4>{sale.corrections.length?sale.corrections.map(c=><p key={c.id}>{dateTime(c.created_at)} · {c.employee||t('Unknown employee')} · {c.reason} · <Money value={c.amount}/> · {t(c.restock?'Stock returned':'No stock returned')}</p>):<p>{t('No corrections')}</p>}
 <h4>{t('Refund history')}</h4>{sale.refunds.length?sale.refunds.map(r=><p key={r.id}>{dateTime(r.created_at)} · {r.employee} · {r.method} · <Money value={r.amount}/> · {r.reason} · {r.reference}</p>):<p>{t('No refunds recorded')}</p>}
 </section>;
}
